### ISSUE TITLE
Selecting 'Create / Edit Podfile' crashes.

### ISSUE THREAD

**Issue by jhoughjr** [kattrali/cocoapods-xcode-plugin#43]
I thought I would use this to edit my Podfile and it crashes every time.
I don't see where to configure anything.

Here is the top of the crash report:

Process:         Xcode [9361]
Path:            /Applications/Xcode.app/Contents/MacOS/Xcode
Identifier:      com.apple.dt.Xcode
Version:         5.1.1 (5085)
Build Info:      IDEFrameworks-5085000000000000~10
App Item ID:     497799835
App External ID: 520942841
Code Type:       X86-64 (Native)
Parent Process:  launchd [143]
Responsible:     Xcode [9361]
User ID:         501

Date/Time:       2014-05-02 22:29:11.844 -0500
OS Version:      Mac OS X 10.9.2 (13C1021)
Report Version:  11
Anonymous UUID:  DF75FAAD-2363-D9D6-F4F8-5F55B5166D3B

Sleep/Wake UUID: 767EB044-16AA-4643-AC8D-343D9F63F2BF

Crashed Thread:  0  Dispatch queue: com.apple.main-thread

Exception Type:  EXC_CRASH (SIGABRT)
Exception Codes: 0x0000000000000000, 0x0000000000000000

Application Specific Information:
Sending createPodfile to <CocoaPods: 0x7fa515024780> from <NSMenuItem: 0x7fa515073390 Create/Edit Podfile>
ProductBuildVersion: 5B1008
UNCAUGHT EXCEPTION (NSInvalidArgumentException): *** -[NSFileManager copyItemAtPath:toPath:error:]: destination path is nil
UserInfo: (null)
Hints: 
  0: Sending createPodfile to <CocoaPods: 0x7fa515024780> from <NSMenuItem: 0x7fa515073390 Create/Edit Podfile>
Backtrace:
  0  0x00007fff8e492244 __exceptionPreprocess (in CoreFoundation)
  1  0x0000000105623b10 DVTFailureHintExceptionPreprocessor (in DVTFoundation)
  2  0x00007fff8ec2be75 objc_exception_throw (in libobjc.A.dylib)
  3  0x00007fff8e49210c +[NSException raise:format:] (in CoreFoundation)
  4  0x00007fff9876857a -[NSFileManager copyItemAtPath:toPath:error:] (in Foundation)
  5  0x00000001110679b4 -[CocoaPods createPodfile] at /Users/jimmyhoughjr/Library/Application Support/Alcatraz/Plug-ins/CocoaPods/cocoadocs/CocoaPods.m:136 (in CocoaPods)
  6  0x00007fff8f0ba340 -[NSApplication sendAction:to:from:] (in AppKit)
  7  0x0000000105b83f85 __37-[DVTApplication sendAction:to:from:]_block_invoke (in DVTKit)
  8  0x0000000105623842 DVTInvokeWithFailureHint (in DVTFoundation)
  9  0x0000000105a51b0e -[DVTApplication sendAction:to:from:] (in DVTKit)
 10  0x00007fff8f0d52a8 -[NSMenuItem _corePerformAction] (in AppKit)
 11  0x00007fff8f0d4fe4 -[NSCarbonMenuImpl performActionWithHighlightingForItemAtIndex:] (in AppKit)
 12  0x00007fff8f12448d -[NSMenu _internalPerformActionForItemAtIndex:] (in AppKit)
 13  0x00007fff8f124309 -[NSCarbonMenuImpl _carbonCommandProcessEvent:handlerCallRef:] (in AppKit)
 14  0x00007fff8f0cb0d6 NSSLMMenuEventHandler (in AppKit)
 15  0x00007fff9418e1d4 DispatchEventToHandlers(EventTargetRec*, OpaqueEventRef*, HandlerCallRec*) (in HIToolbox)
 16  0x00007fff9418d787 SendEventToEventTargetInternal(OpaqueEventRef*, OpaqueEventTargetRef*, HandlerCallRec*) (in HIToolbox)
 17  0x00007fff941a1880 SendEventToEventTarget (in HIToolbox)
 18  0x00007fff941d7640 SendHICommandEvent(unsigned int, HICommand const*, unsigned int, unsigned int, unsigned char, void const*, OpaqueEventTargetRef*, OpaqueEventTargetRef*, OpaqueEventRef**) (in HIToolbox)
 19  0x00007fff9420a238 SendMenuCommandWithContextAndModifiers (in HIToolbox)
 20  0x00007fff9420a1e0 SendMenuItemSelectedEvent (in HIToolbox)
 21  0x00007fff9420a0bf FinishMenuSelection(SelectionData*, MenuResult*, MenuResult*) (in HIToolbox)
 22  0x00007fff94212095 MenuSelectCore(MenuData*, Point, double, unsigned int, OpaqueMenuRef**, unsigned short*) (in HIToolbox)
 23  0x00007fff94211cc1 _HandleMenuSelection2 (in HIToolbox)
 24  0x00007fff8f03d73c _NSHandleCarbonMenuEvent (in AppKit)
 25  0x00007fff8ee9c6be _DPSNextEvent (in AppKit)
 26  0x00007fff8ee9ba2b -[NSApplication nextEventMatchingMask:untilDate:inMode:dequeue:] (in AppKit)
 27  0x0000000105b83631 -[DVTApplication nextEventMatchingMask:untilDate:inMode:dequeue:] (in DVTKit)
 28  0x00007fff8ee8fb2c -[NSApplication run] (in AppKit)
 29  0x00007fff8ee7a913 NSApplicationMain (in AppKit)
 30  0x00007fff91e2b5fd start (in libdyld.dylib)

**Comment by Diwann** [comment]
same for me when I click on "Create/Edit Podspec"

**Comment by jd-alexander** [comment]
Having this issue too. Seems this isn't getting fixed anytime soon.

**Comment by kattrali** [comment]
I haven't had maintenance time to dedicate to this project in a while. I'm not sure when things will clear up.
