### ISSUE TITLE
CocoaPods option not showing

### ISSUE THREAD

**Issue by sohayb** [kattrali/cocoapods-xcode-plugin#56]
After updating to the latest Xcode version 6.3, I reinstalled Alctraz.io plugin the removed and reinstalled the CocoaPods plugin (because the option was not showing in the product menu). After restarting Xcode, the CocoaPods option is still missing from the product menu. Is there any fix for this problem yet?
Thanks

**Comment by linked67** [comment]
There is a pull request that should fix it, i hope they will commit it soon

**Comment by bkeet** [comment]
Have a similar issue, am using Alcatraz manager and if I remove/install then CocoaPods appears in the menu, but if I restart Xcode it disappears.

**Comment by kattrali** [comment]
Fixed.
