### ISSUE TITLE
CocoPods option not showing in Xcode 6.3.2

### ISSUE THREAD

**Issue by bkeet** [kattrali/cocoapods-xcode-plugin#61]
After updating to the latest Xcode version 6.3.2, I reinstalled the Alcatraz plugin then removed and reinstalled the CocoaPods plugin (option was not showing in the product menu). After restarting Xcode, the CocoaPods option is still missing from the product menu. Appears to be a similar issue as before...

**Comment by kattrali** [comment]
Yes, this will happen every time a new version of Xcode is released. Fixed!
