### ISSUE TITLE
Menu option doesn't appear on XCode 6.3.2

### ISSUE THREAD

**Issue by heypaulmcgrath** [kattrali/cocoapods-xcode-plugin#62]
I installed the plugin via [Alcatraz][link], but the latest version doesn't seem to work. Apologies if i'm missing something.

[link]: http://alcatraz.io/

**Comment by twox** [comment]
I have the same problem with XCode 6.3.2

**Comment by StephenZhuang** [comment]
I installed the plugin via clone the project and build, but i have the same problem with XCode 6.3.2

**Comment by neilkachu** [comment]
Same here, updated DVTPlugInCompatibilityUUID's  to 6.3.2 value in plugin's Info.plist, no effect this time.

**Comment by deksden** [comment]
Here is same issues with XCode 6.4 / 6.3.2(?) and Dash plugin - https://github.com/omz/Dash-Plugin-for-Xcode/issues/37

they have solution: https://github.com/omz/Dash-Plugin-for-Xcode/commit/3014f12c4e91a6be3a0521600f65879acae05b0a

**Comment by kattrali** [comment]
Ah, I'm on it. Thanks!

**Comment by kattrali** [comment]
Fixed by #63! :beers:
