### ISSUE TITLE
Xcode Start Slowly

### ISSUE THREAD

**Issue by codwam** [kattrali/cocoapods-xcode-plugin#64]
I Found a ploblem that is xcode start slowly when I install your plugin,about 5 minutes or more.And others will not.
os x 10.10.3,
xcode 6.3.2

**Comment by kattrali** [comment]
Was this fixed? Or some other issue?

**Comment by culmek** [comment]
no fix but i closed

**Comment by codwam** [comment]
It's also a problem that start slowly when I open Xcode firstly...

**Comment by vijaymason** [comment]
I have the same problem, Xcode will bounce on dock for 2-5 mins before opening. If I remove cocoa pods then there is no problem.

**Comment by kattrali** [comment]
Thanks @codwam, @vijaymason. Can you confirm your Xcode version and OS X version? In addition, what other packages are installed? I have not yet been able to reproduce this bug but am trying. :)

**Comment by vijaymason** [comment]
Hi Delisa,

OS X El Capitan 10.11.1
Xcode 7.1.1 (7B1005)

No other packages installed just CocoaPods


> On 17 Nov 2015, at 18:37, Delisa Mason <notifications@github.com> wrote:
> 
> Thanks @codwam <https://github.com/codwam>, @vijaymason <https://github.com/vijaymason>. Can you confirm your Xcode version and OS X version? In addition, what other packages are installed? I have not yet been able to reproduce this bug but am trying. :)
> 
> —
> Reply to this email directly or view it on GitHub <https://github.com/kattrali/cocoapods-xcode-plugin/issues/64#issuecomment-157463849>.
> 


Kind regards,

Vijay Mason

**Comment by kattrali** [comment]
@vijaymason Well, I'd assume you have Alcatraz installed as well, correct?

**Comment by vijaymason** [comment]
Hi Delisa,

Yes that is correct, i have iMac 5K Retina aswell :)

> On 17 Nov 2015, at 18:43, Delisa Mason <notifications@github.com> wrote:
> 
> @vijaymason <https://github.com/vijaymason> Well, I'd assume you have Alcatraz installed as well, correct?
> 
> —
> Reply to this email directly or view it on GitHub <https://github.com/kattrali/cocoapods-xcode-plugin/issues/64#issuecomment-157466315>.
> 


Kind regards,

Vijay Mason

**Comment by kattrali** [comment]
Didn't actually mean to close this. Pushed a possible fix in 564fbc1, though I'll need it confirmed.

**Comment by vijaymason** [comment]
Seems to have fixed the issue :)

**Comment by kattrali** [comment]
Awesome! Thanks.
