### ISSUE TITLE
Resolved command path for "pod" is invalid.  Expanded GEM_PATH: /usr/bin

### ISSUE THREAD

**Issue by kohdesmond** [kattrali/cocoapods-xcode-plugin#73]
Hi Kattrali,

This might be a simple question, but I can't seem to fix it.

What should i change to make install pod works?

**Comment by LSsoftware** [comment]
I have same Issue.

**Comment by kattrali** [comment]
Hi @kohdesmond, @LSsoftware, do you have the cocoapods gem installed? What do you see when you run these commands in a terminal:

1. `which ruby`
2. `which pod`

By default, the plugin looks for Cocoapods to be installed at `/usr/bin/pod`, which should happen when you run `gem install cocoapods` using the default ruby command on OS X (`/usr/bin/ruby`). 

If `/usr/bin/pod` does not exist and you do have cocoapods installed, you can instead replace `GEM_PATH` in the menu (Product > Cocoapods > GEM_PATH) with the output of the command `which pod`. Let me know if this helps!

**Comment by bre7** [comment]
Thanks @kattrali. In my case it was `/usr/local/bin/` instead (not sure why...It was working fine until I upgraded to El Capitan)

**Comment by kohdesmond** [comment]
@kattrali, in my case it /usr/bin/ruby & /usr/local/bin/pod running El Capitan too..

**Comment by LSsoftware** [comment]
@kattrali , i reinstall ruby many many times, i finally solved the issues. Also thank you.

**Comment by kattrali** [comment]
@LSsoftware awesome! glad to help.

@kohdesmond Does changing `GEM_PATH` to `/usr/bin/local` fix your issue? I'll update the pod command to use `/usr/local/bin/pod` if that is the new default.

**Comment by kohdesmond** [comment]
@kattrali, yes it does work for me by using /usr/local/bin/
i'm closing this issue Thanks!

**Comment by macecchi** [comment]
I had to update GEM_PATH after reinstalling CocoaPods on OS X El Capitan, even though I never reinstalled Ruby and the path for `which ruby` remains the default. pod was now installed under `/usr/local/bin/pod`. Maybe this is a new default?

**Comment by kattrali** [comment]
Ah, thanks @macecchi, that helps!

**Comment by goktugyil** [comment]
I just updated. I uninstalled and reinstalled this plugin from package manager. I tried:

/usr/local/bin/
/usr/local/bin/pod

Both didnt work

**Comment by goktugyil** [comment]
https://github.com/CocoaPods/CocoaPods/issues/3736#issuecomment-146675101

After this it worked with /usr/local/bin/

**Comment by jayjayesh** [comment]
yes,  it worked with /usr/local/bin/
thanks goktugyil
