### ISSUE TITLE
The command path could not be resolved

### ISSUE THREAD

**Issue by codwam** [kattrali/cocoapods-xcode-plugin#76]
Resolved command path for "pod" is invalid.

Expanded GEM_PATH: /usr/bin

Above is error msg while clicked update Pods..
I have install xcode6.4 and xcode7 in ei capitan

**Comment by kattrali** [comment]
Hi @culmek, do you have the cocoapods gem installed? What do you see when you run these commands in a terminal:

1. `which ruby`
2. `which pod`

By default, the plugin looks for Cocoapods to be installed at `/usr/bin/pod`, which should happen when you run `gem install cocoapods` using the default ruby command on OS X (`/usr/bin/ruby`). 

According to some comments in #73, if you are running El Capitan, the default GEM_PATH is now `/usr/local/bin`. You can also try setting GEM_PATH to that and see if it helps.

If `/usr/bin/pod` and `/usr/local/bin/pod` do not exist and you do have cocoapods installed, you can instead replace `GEM_PATH` in the menu (Product > Cocoapods > GEM_PATH) with the output of:

```bash
dirname `which pod`
```

Let me know if this helps!

**Comment by nkhaddari** [comment]
dirname `which pod`, works for me perfectly!

**Comment by Skornos** [comment]
/usr/local/bin works, thanks

**Comment by codwam** [comment]
up is answer, thanks

**Comment by AppDev666** [comment]
/usr/local/bin works, thanks

**Comment by MCLeehuan** [comment]
works for me，thx!
