### ISSUE TITLE
OS X EI Capitan xCode7 issues

### ISSUE THREAD

**Issue by shiqyn** [kattrali/cocoapods-xcode-plugin#78]
when click update pods, it say"Resolved command path for pod is invalid  expanded GEM_PATH:/user/bin"

**Comment by duffek** [comment]
same here

**Comment by kattrali** [comment]
This may resolve your issue: https://github.com/kattrali/cocoapods-xcode-plugin/issues/76#issuecomment-145579390

Can you verify?

**Comment by kattrali** [comment]
Fixed by 05057d4.
